### ISSUE TITLE
Allow Cypress version to be configurable

### ISSUE THREAD

**Issue by vikikamath** [wimdeblauwe/testcontainers-cypress#20]
Current version (1.0.0) uses [cypress-version](https://github.com/wimdeblauwe/testcontainers-cypress/blob/master/src/main/java/io/github/wimdeblauwe/testcontainers/cypress/CypressContainer.java#L26).

However, sometimes you want to run this in a CI/CD agent (with a preinstalled Cypress binary) without having to wait for a non-existing Cypress binary to be downloaded by this module.

**Comment by wimdeblauwe** [comment]
You can select the docker image you want to use via [this constructor](https://github.com/wimdeblauwe/testcontainers-cypress/blob/master/src/main/java/io/github/wimdeblauwe/testcontainers/cypress/CypressContainer.java#L50). Or do you mean something else?
