### ISSUE TITLE
How to pass the --record --key $ key command for my cypress container

### ISSUE THREAD

**Issue by PauloBragaOtimize-e** [wimdeblauwe/testcontainers-cypress#23]
I use testcontainers-cypress to run my application tests. we recently started using the Cypress Dashboard in our local runs and would like to use it in our runs with the testcontainer. As described in the Title, so that our executions can be displayed on the Cypress Dashboard, it is necessary to run the tests with the following command "cypress run --record --key $ KEY". Reading the testcontainer documentation I tried some successful solutions like

.withCommand ("--record --key $ KEY")

.withCreateContainerCmdModifier (cmd ->
                        cmd.withEntrypoint ("cypress run --record --key $ KEY"))

but all to no avail.

How can I do this ???

NOTE: I pass $KEY as an environment variable with .withEnv ()

**Comment by wimdeblauwe** [comment]
I will release a 1.2.0 as soon as possible, but there is a problem with Maven Central unfortunately currently.

**Comment by wimdeblauwe** [comment]
Version 1.2.0 is available now: https://search.maven.org/artifact/io.github.wimdeblauwe/testcontainers-cypress/1.2.0/jar
